spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user-service
    username: postgres
    password: admin
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/mock-data

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - health
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
