spring:
  profiles:
    active: dev
  mvc:
    problemdetails:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        check_nullability: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false


application:
  constraints:
    user:
      age:
        min: 18