name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - '*'

permissions:
  # Required for test-reporter
  contents: read
  actions: read
  checks: write

jobs:

  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build
        uses: ./.github/actions/main-build
        with:
          test-reporter-job-name: Linux test results

